import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import chalk from "chalk";

// --- Helper Functions ---
function ensureDirExists(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function writeFile(filePath, content) {
  fs.writeFileSync(filePath, content.trim() + "\n", "utf-8");
}

/**
 * تابع اصلی ساخت پروژه با قابلیت Swagger داینامیک و Auth کامل
 */
export async function makeProject(rootPath, config) {
  try {
    console.log(chalk.blue(`\n🚀 Building Niki project: ${rootPath}`));

    const srcPath = path.join(rootPath, "src");
    const dirs = [
      srcPath,
      path.join(srcPath, "config"),
      path.join(srcPath, "models"),
      path.join(srcPath, "repositories"),
      path.join(srcPath, "controllers"),
      path.join(srcPath, "routes"),
      path.join(srcPath, "middlewares"),
      path.join(srcPath, "validations"),
    ];

    dirs.forEach(ensureDirExists);

    // ۱. مدیریت package.json
    const packageJsonPath = path.join(rootPath, "package.json");
    let pkg = fs.existsSync(packageJsonPath) ? JSON.parse(fs.readFileSync(packageJsonPath, "utf-8")) : {};

    pkg.name = pkg.name || config.project.name || "niki-api";
    pkg.version = pkg.version || "1.0.0";
    pkg.type = "module";
    pkg.scripts = {
      ...pkg.scripts,
      "start": "node src/server.js",
      "dev": "nodemon src/server.js"
    };

    pkg.dependencies = pkg.dependencies || {};
    const deps = ["express", "mongoose", "dotenv", "cors", "helmet", "joi", "swagger-ui-express", "swagger-jsdoc"];
    if (config.auth?.enabled) deps.push("jsonwebtoken", "bcryptjs");
    
    deps.forEach((d) => { if (!pkg.dependencies[d]) pkg.dependencies[d] = "latest"; });
    pkg.devDependencies = { ...pkg.devDependencies, "nodemon": "latest" };

    writeFile(packageJsonPath, JSON.stringify(pkg, null, 2));

    // ۲. فایل‌های اصلی (Env, DB, Swagger Config)
    writeFile(path.join(rootPath, ".env"), `PORT=${config.project.port || 5000}\nMONGO_URI=${config.database?.uri || "mongodb://localhost:27017/niki_db"}\nJWT_SECRET=${config.auth?.secret || "niki_secret_key"}`);
    
    writeFile(path.join(srcPath, "config", "db.js"), `
import mongoose from 'mongoose';
export const connectDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('✔ MongoDB Connected');
    } catch (error) {
        console.error('✘ Database Error:', error.message);
        process.exit(1);
    }
};`);

    writeFile(path.join(srcPath, "config", "swagger.js"), `
import swaggerJsdoc from 'swagger-jsdoc';

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: '${config.project.name || "Niki API"}',
      version: '1.0.0',
      description: 'API Documentation generated by Niki CLI',
    },
    servers: [{ url: 'http://localhost:${config.project.port || 5000}/api' }],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }
      }
    }
  },
  apis: ['./src/routes/*.js'],
};

export const swaggerSpec = swaggerJsdoc(options);`);

    // ۳. میدلویرها
    writeFile(path.join(srcPath, "middlewares", "error.middleware.js"), `
export const errorHandler = (err, req, res, next) => {
    const statusCode = res.statusCode === 200 ? 500 : res.statusCode;
    res.status(statusCode).json({ message: err.message });
};`);

    // ۴. پیاده‌سازی سیستم Auth (اگر فعال باشد)
    if (config.auth?.enabled) {
      // Middleware
      writeFile(path.join(srcPath, "middlewares", "auth.middleware.js"), `
import jwt from 'jsonwebtoken';
export const protect = async (req, res, next) => {
    let token = req.headers.authorization?.startsWith('Bearer') ? req.headers.authorization.split(' ')[1] : null;
    if (!token) return res.status(401).json({ message: 'Not authorized' });
    try {
        req.user = jwt.verify(token, process.env.JWT_SECRET);
        next();
    } catch (e) { res.status(401).json({ message: 'Invalid token' }); }
};`);

      // Auth Controller
      writeFile(path.join(srcPath, "controllers", "auth.controller.js"), `
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import User from '../models/user.model.js';

const generateToken = (id) => jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: '30d' });

export const register = async (req, res, next) => {
    try {
        const { email, password, fullName } = req.body;
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);
        const user = await User.create({ email, password: hashedPassword, fullName });
        res.status(201).json({ token: generateToken(user._id) });
    } catch (e) { next(e); }
};

export const login = async (req, res, next) => {
    try {
        const { email, password } = req.body;
        const user = await User.findOne({ email });
        if (user && (await bcrypt.compare(password, user.password))) {
            res.json({ token: generateToken(user._id) });
        } else {
            res.status(401);
            throw new Error('Invalid email or password');
        }
    } catch (e) { next(e); }
};`);

      // Auth Routes with Swagger
      writeFile(path.join(srcPath, "routes", "auth.routes.js"), `
import { Router } from 'express';
import * as ctrl from '../controllers/auth.controller.js';
const router = Router();

/**
 * @swagger
 * /auth/register:
 *   post:
 *     summary: Register a new user
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, password]
 *             properties:
 *               email: { type: string }
 *               password: { type: string }
 *               fullName: { type: string }
 *     responses:
 *       201:
 *         description: Success
 */
router.post('/register', ctrl.register);

/**
 * @swagger
 * /auth/login:
 *   post:
 *     summary: Login user
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [email, password]
 *             properties:
 *               email: { type: string }
 *               password: { type: string }
 *     responses:
 *       200:
 *         description: Success
 */
router.post('/login', ctrl.login);
export default router;`);
    }

    // ۵. تولید انتیتی‌ها
    if (config.entities) {
      for (const entity of config.entities) {
        await generateEntityFiles(srcPath, entity, config.auth?.enabled);
      }
    }

    updateRoutesIndex(srcPath);

    // ۶. فایل سرور اصلی
    writeFile(path.join(srcPath, "server.js"), `
import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import helmet from 'helmet';
import swaggerUi from 'swagger-ui-express';
import { connectDB } from './config/db.js';
import { swaggerSpec } from './config/swagger.js';
import apiRoutes from './routes/index.js';
import { errorHandler } from './middlewares/error.middleware.js';

dotenv.config();
connectDB();

const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors());
app.use(express.json());

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use('/api', apiRoutes);
app.use(errorHandler);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(\`🚀 Server: http://localhost:\${PORT}\`);
    console.log(\`📖 Swagger: http://localhost:\${PORT}/api-docs\`);
});`);

    console.log(chalk.cyan("\n📦 Installing dependencies..."));
    execSync("npm install", { cwd: rootPath, stdio: "inherit" });
    return { success: true };
  } catch (err) {
    console.error(chalk.red("Generation error:"), err);
    return { success: false };
  }
}

async function generateEntityFiles(srcPath, entity, authEnabled) {
  const { name, fields } = entity;
  const nameL = name.toLowerCase();

  // --- Model Generation ---
  const modelFields = fields.map(f => {
    let type = f.type === 'ObjectId' ? 'mongoose.Schema.Types.ObjectId' : f.type;
    return `    ${f.name}: { type: ${type}${f.ref ? `, ref: '${f.ref}'` : ""}, required: ${f.required} }`;
  }).join(",\n");
  writeFile(path.join(srcPath, "models", `${nameL}.model.js`), `import mongoose from 'mongoose';\nconst schema = new mongoose.Schema({\n${modelFields}\n}, { timestamps: true });\nexport default mongoose.model('${name}', schema);`);

  // --- Repository Generation ---
  writeFile(path.join(srcPath, "repositories", `${nameL}.repository.js`), `
import M from '../models/${nameL}.model.js';
export class ${name}Repository {
    async create(d) { return await M.create(d); }
    async getAll() { return await M.find(); }
    async getById(id) { return await M.findById(id); }
    async update(id, d) { return await M.findByIdAndUpdate(id, d, { new: true }); }
    async delete(id) { return await M.findByIdAndDelete(id); }
}`);

  // --- Controller Generation ---
  writeFile(path.join(srcPath, "controllers", `${nameL}.controller.js`), `
import { ${name}Repository } from '../repositories/${nameL}.repository.js';
const repo = new ${name}Repository();
export const create = async (req, res, next) => { try { res.status(201).json(await repo.create(req.body)); } catch (e) { next(e); } };
export const getAll = async (req, res, next) => { try { res.json(await repo.getAll()); } catch (e) { next(e); } };
export const getById = async (req, res, next) => { try { res.json(await repo.getById(req.params.id)); } catch (e) { next(e); } };
export const update = async (req, res, next) => { try { res.json(await repo.update(req.params.id, req.body)); } catch (e) { next(e); } };
export const remove = async (req, res, next) => { try { await repo.delete(req.params.id); res.json({ message: 'Deleted' }); } catch (e) { next(e); } };`);

  // --- Validation Generation ---
  const joiFields = fields.map(f => {
    let type = f.type.toLowerCase().includes('objectid') ? 'string' : f.type.toLowerCase();
    return `    ${f.name}: Joi.${type}().${f.required ? 'required()' : 'optional()'}`;
  }).join(",\n");
  writeFile(path.join(srcPath, "validations", `${nameL}.validation.js`), `import Joi from 'joi';\nexport const validate = (req, res, next) => {\n    const { error } = Joi.object({\n${joiFields}\n    }).validate(req.body);\n    if (error) return res.status(400).json({ message: error.details[0].message });\n    next();\n};`);

  // --- Swagger Generation for Entity ---
  const swaggerProps = fields.map(f => ` *           ${f.name}:\n *             type: ${f.type === 'Number' ? 'number' : f.type === 'Boolean' ? 'boolean' : 'string'}`).join("\n");
  
  const swaggerDoc = `
/**
 * @swagger
 * components:
 *   schemas:
 *     ${name}:
 *       type: object
 *       properties:
${swaggerProps}
 * 
 * /${nameL}s:
 *   get:
 *     summary: Get all ${nameL}s
 *     tags: [${name}]
 *     responses:
 *       200:
 *         description: Success
 *   post:
 *     summary: Create ${nameL}
 *     tags: [${name}]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/${name}'
 *     responses:
 *       201:
 *         description: Created
 */`;

  // --- Routes Generation ---
  const authImp = authEnabled ? "import { protect } from '../middlewares/auth.middleware.js';\n" : "";
  const mid = authEnabled ? "protect, " : "";
  writeFile(path.join(srcPath, "routes", `${nameL}.routes.js`), `
import { Router } from 'express';
import * as ctrl from '../controllers/${nameL}.controller.js';
import { validate } from '../validations/${nameL}.validation.js';
${authImp}
const router = Router();
${swaggerDoc}
router.route('/').get(ctrl.getAll).post(${mid}validate, ctrl.create);
router.route('/:id').get(ctrl.getById).put(${mid}validate, ctrl.update).delete(${mid}ctrl.remove);
export default router;`);
}

export function updateRoutesIndex(srcPath) {
  const routesDir = path.join(srcPath, "routes");
  ensureDirExists(routesDir);
  const files = fs.readdirSync(routesDir).filter(f => f.endsWith(".routes.js") && f !== "index.js");
  let imports = "", uses = "";
  
  // اولویت با روت Auth اگر وجود داشته باشد
  if (fs.existsSync(path.join(routesDir, "auth.routes.js"))) {
    imports += `import authRoutes from './auth.routes.js';\n`;
    uses += `router.use('/auth', authRoutes);\n`;
  }

  files.forEach(f => {
    if (f === "auth.routes.js") return;
    const n = f.split('.')[0];
    imports += `import ${n}Routes from './${f}';\n`;
    uses += `router.use('/${n}s', ${n}Routes);\n`;
  });

  writeFile(path.join(routesDir, "index.js"), `import { Router } from 'express';\n${imports}\nconst router = Router();\n${uses}export default router;`);
}

export async function addModel(rootPath, modelName, fields = []) {
  const srcPath = path.join(rootPath, "src");
  const auth = fs.existsSync(path.join(srcPath, "middlewares", "auth.middleware.js"));
  await generateEntityFiles(srcPath, { name: modelName, fields }, auth);
  updateRoutesIndex(srcPath);
}

export async function removeModel(rootPath, modelName) {
  const srcPath = path.join(rootPath, "src");
  const nl = modelName.toLowerCase();
  ["models", "repositories", "controllers", "routes", "validations"].forEach(d => {
    const ext = d === 'routes' ? 'routes' : d.slice(0, -1);
    const f = path.join(srcPath, d, `${nl}.${ext}.js`);
    if (fs.existsSync(f)) fs.unlinkSync(f);
  });
  updateRoutesIndex(srcPath);
}
